image: python:3.10

stages:
  - test

test_flask_app:
  stage: test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
    - pip install pytest
    - pytest tests/