image: python:3.10

stages:
  - test

test_flask_app:
  stage: test
  script:
    - python -m venv venv               # create virtual environment
    - source venv/bin/activate         # activate virtual environment
    - pip install --upgrade pip        # upgrade pip inside venv
    - pip install -r requirements.txt # install dependencies inside venv
    - pip install pytest               # make sure pytest is installed
    - pytest tests/                   # run tests folder with pytest
