image: python:3.10

stages:
  - test
  - deploy

variables:
  APP_DIR: /home/ubuntu/myapp               
  EC2_HOST: ec2-3-76-124-56.eu-central-1.compute.amazonaws.com  
  SSH_USER: ubuntu

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - export PYTHONPATH="${PYTHONPATH}:$(pwd)"

test_flask_app:
  stage: test
  script:
    - pip install pytest
    - pytest tests/

deploy_to_ec2:
  stage: deploy
  script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 600 id_rsa
    - rsync -avz -e "ssh -i id_rsa -o StrictHostKeyChecking=no" ./ $SSH_USER@$EC2_HOST:$APP_DIR
    - ssh -i id_rsa -o StrictHostKeyChecking=no $SSH_USER@$EC2_HOST "cd $APP_DIR && sudo systemctl restart flaskapp.service"
  only:
    - main
