services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile  
    ports:
      - "81:81"
    networks:
      - app-network

  flask:
    build:
      context: .
      dockerfile: frontend.Dockerfile  
    ports:
      - "80:80"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
